version: "3"
services:
  node-install:
    build:
      dockerfile: Dockerfile-install
      context: ./web-content
    image: alexsimons/webflux-node-install:9.2.0
    entrypoint:
      - npm
      - install
    volumes:
      - ./web-content:/app

#runs the node install